paymnd:
  # ping middleware is needet in feature when we have png backs rom vendors
  # at now only the ping.path is in use for the middleware links
  ping:
    url:
      # host will be used in redirect links
      host: "localhost:1337"
      protocol: "http"
      pathname: "/payment"

    api:
      apikey: "xyz123"
      secret:

  # Vendor must correct match with vendor path name
  vendor:
    paypal:
      # option is reserved keyword to use as payment global options
      # option are default and can be overwrite with method options
      options:
        currency: "EUR"

        api:
          host: "api.sandbox.paypal.com"
          client_id: "YOUR_PAYPAL_CLIENT_ID"
          client_secret: "YOUR_PAYPAL_CLIENT_SECRET"

        redirectUrl:
          # cancel_url is when user click back to shop
          cancel: "/cancel"
          success: "/success"
          error: "/error"

      # multiple methods:
      method:
        # payment method: payment name must match with the js file in vendor
        paypal:
          # method name must be unique
          methodName: "paypal"
          # title is optional nad overwrite the hardcoded name
          title: "Paypal Deutschland"

        # payment method: payment name must match with the js file in vendor
        creditcard:
          # method name must be unique
          methodName: "paypal_creditcard"
          # title is optional nad overwrite the hardcoded name
          title: "Paypal Kreditkarte Deutschland"

    sepa:
      title: "Lastschrift"
      options:
        currency: "EUR"

    saferpay:
      title: "SaferPAY"
       # method name must be unique
      methodName: "saferkadabra"
      options:
        currency: "EUR"
        accountId: "SAFERPAY_ACCOUNTID"
        # additional params append to query params
        query:
          CCCVC: "yes"
          CCNAME: "yes"
          DESCRIPTION: "TEMP_DESCRIPTION"

        gateway:
          payInit: "https://www.saferpay.com/hosting/CreatePayInit.asp"
          payConfirm: "https://www.saferpay.com/hosting/VerifyPayConfirm.asp"
          payComplete: "https://www.saferpay.com/hosting/PayComplete.asp"

        redirectUrl:
          cancel: "/cancel"
          success: "/success"
          error: "/error"

        # Special for testaccount: Passwort for hosting-capture neccessary.
        # Not needed for standard-saferpay-eCommerce-accounts
        # activate it on testing/development account

        #spPassword: "PASSWORD"


  #    # single payment method: payment name must match with the js file in vendor
  #    paypal:
  #      # method is optional if it is set, then it overwrite payment method name
  #      method: "paypal"
  #      # title is optional nad overwrite the hardcodet name
  #      title: "Paypal Deutschland"

  # if you have not ready connection, then
  # set your mongo credentials to create own connection
  db:
    mongo:
      uri:   "localhost:27017/paymnd"
      options:
        user: "root"
        pass: ""


server:
  # server name to listen is used in example or standalone
  server: "localhost"
  # server port where to listen
  port: 1337

#########################################################
# this is nor relavant for you and only use for example #
#########################################################



debug:
  verbose: false
  level: "paymnd:*"

