"use strict";

const CREDITCARD_CHECK_FAILD = 2000;
const CREDITCARD_NUMBER = 2001;
const CREDITCARD_YEAR = 2002;
const CREDITCARD_MOINTH = 2003;

module.exports = {
  CREDITCARD_CHECK_FAILD,
  CREDITCARD_NUMBER,
  CREDITCARD_YEAR,
  CREDITCARD_MOINTH
};